server:
  port: 60456

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/sea?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: adminmysql
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 60
        max-idle: 8
        min-idle: 0
    timeout: 10000

# JWT 配置
#jwt configuration
jwt:
  tokenHeader: accessToken
  authHeader: authorities
  tokenPrefix: Bearer
  secret: sexygirls
  #minutes
  expiration: 60
  antMatchers: /index,/login,/security/noauth,/swagger/**,/webjars/**,/swagger-resources/**,/v2/api-docs,/**/*.html,/exception/**,/lombok,/favicon.ico,/api/**,/jpa/**,/mybatis/**,/redis/**,/mongo/**

mybatis:
  config-location: classpath*:mybatis-config.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  type-aliases-package: com.chried.sea.*.model.entity
  # 配置日志打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl